### ISSUE TITLE
Transaction and Mining issues. 

### ISSUE THREAD

**Issue by vishal2241** [rubixchain/rubixnetwork#3]
![Screenshot_20220417-212109_Termius](https://user-images.githubusercontent.com/16206442/163722184-dade49d5-e173-461d-85ab-04177468ff0b.jpg)

This same reciever is getting a lot of transactions but when we try to send test amount to same reciever , it says that latest jar is not running in reciever. How the reciever is getting it from other senders when latest jar is not running in it. Also what is sender authentication failed and why it fails. You can match times in SS. I am sharing them as requested by team on TG. Opening issues on Git repository so you need not to reply to everyone personally and ask everyone to mail maintainers with logs.  you can take full utilisation of git here itself. More Open source. 

This same problem is coming in every reciever currently mining . Another issue is that it says that type 1 mining is no more supported , please select subnet for mining. So basically only those who have private subnet will be able to mine. What about 13000 nodes who are running individually ? Or majority of nodes are owned by team.

**Comment by vishal2241** [comment]
![Screenshot_20220417-213238_Termius](https://user-images.githubusercontent.com/16206442/163722701-aa15a597-5ac0-4698-8e80-7077e8020ae2.jpg)

**Comment by gklps** [comment]
Hi @vishal2241,
Thanks for connecting with the team.
In order to resolve your issue, we would need the following information:

1. Which jar version is the Sender running?
2. Which jar version is the Receiver running?
3. Which is the OS both Sender and Receiver are running?
4. For the following command are you getting a status code other than 200?
             ```
             curl localhost:1898/getAccountInfo
              ```
5. Did you try doing a transaction after restarting the Jar & IPFS?
6. Is this the first transaction you did from the above Sender?

**Comment by vishal2241** [comment]
Hi , 

Thanks for your reply. 
1. Sender is running 1.9.3
2. Reciever i am not sure as i tried it with a random receiver whose transaction is showing regularly on rubixexplorer. 
3. Os for sender is ubuntu 20.04
4. getAccountInfo shows complete balance , did , etc
5. Yeah. It remains same. 
6. No , its not the first transction. But with version 1.9.3 , its first.

**Comment by gklps** [comment]
Hi @vishal2241 ,
Thanks for sharing all the info, we recommend you update the wallet to the latest version.
Before initiating a transaction you can try to validate the receiver using the following commands

```
$ curl --location --request GET "localhost:1898/validateReceiver?receiverDID=<>"
```

Kindly verify if the sender and receiver are getting same response for the below command

```
$ curl localhost:1898/getVersion
```
